version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_TOKEN: ${S3_ACCESS_TOKEN}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    volumes:
      - .:/app
      - /tmp/uploads:/tmp/uploads
