version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      S3_BUCKET_NAME: urancam-talcjp
      S3_ENDPOINT: https://aae5acc7f9c7cdb2f332939bc0f356ca.r2.cloudflarestorage.com
      S3_ACCESS_TOKEN: e50ab5fb132c0373d8a88d57610122f2
      S3_SECRET_KEY: 3483a411dce7272dca64413f7d2349c6afda213a7b80510a7f4ae523cce640f8
    volumes:
      - .:/app
      - /tmp/uploads:/tmp/uploads
